// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDX820kQcpDVDnLSTdnp799VXWQpD4To60',
    appId: '1:881258448510:web:5d5911520da237bd047a2f',
    messagingSenderId: '881258448510',
    projectId: 'morningmovies-5c311',
    authDomain: 'morningmovies-5c311.firebaseapp.com',
    storageBucket: 'morningmovies-5c311.appspot.com',
    measurementId: 'G-6R3Z81K95T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJpnjlWVESM2FxSItVFm5LzV7W6qqI94U',
    appId: '1:881258448510:android:0b6653b95e34c929047a2f',
    messagingSenderId: '881258448510',
    projectId: 'morningmovies-5c311',
    storageBucket: 'morningmovies-5c311.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrwksQ-opGsXALDlPg-b2cq4R1iuHM0K4',
    appId: '1:881258448510:ios:f4f11060fdd4dac1047a2f',
    messagingSenderId: '881258448510',
    projectId: 'morningmovies-5c311',
    storageBucket: 'morningmovies-5c311.appspot.com',
    iosBundleId: 'com.example.helloWorld',
  );
}
